/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BaiTapBauCuaTomCa;

import java.awt.Image;
import java.util.ArrayList;
import java.util.Random;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class JBaiTapBauCuaTomCa extends javax.swing.JFrame {

    /**
     * Creates new form JBaiTapBauCuaTomCa
     */
    ArrayList<Integer> DayRandom;
    Vector tblData = new Vector();
    Vector tblTitle = new Vector();
    public JBaiTapBauCuaTomCa() {
        initComponents();
        create_cboChon();
        bangBauCua();
        tblBang.setModel(new DefaultTableModel(null, tblTitle));
    }

    public void create_cboChon(){
        String[] str = {"Nai","Bầu","Mèo","Cá","Cua","Tôm"};
        for(String i:str){
            cboChon.addItem(i);
        }
    }
    
    public void bangBauCua(){
        tblTitle.add("STT"); tblTitle.add("Cược"); tblTitle.add("Tiền cược"); 
        tblTitle.add("Tình trạng"); tblTitle.add("Số tiền còn"); 
    }
    
    public void laydulieuBauCua(ArrayList<Integer> dsrandom){
        int j = tblBang.getRowCount();
        String Cuoc = cboChon.getSelectedItem().toString();
        int TienCuoc = Integer.parseInt(txtTienCuoc.getText());
        if(TienCuoc>Integer.parseInt(txtTienConLai.getText()))
            JOptionPane.showMessageDialog(this, "Số tiền cược đã lớn hơn số tiền còn");
        else{
            String tinhtrang = setTinhTrang(dsrandom);
            int SoTienCon = 0;
            if(tinhtrang=="Thua")
                SoTienCon = Integer.parseInt(txtTienConLai.getText())-TienCuoc;
            else
                SoTienCon = Integer.parseInt(txtTienConLai.getText())+TienCuoc;
            txtTienConLai.setText(SoTienCon+"");
            Vector v = new Vector();
            v.add(j+1); 
            v.add(Cuoc); 
            v.add(TienCuoc); 
            v.add(tinhtrang);
            v.add(SoTienCon);
            j++;
            tblData.add(v);
            tblBang.setModel(new DefaultTableModel(tblData, tblTitle));
        }
    }
    
    public String setTinhTrang(ArrayList<Integer> dsrandom){
        int cuoc = cboChon.getSelectedIndex()+1;
        String tinhtrang = "Thua";
        for(int i:dsrandom){
            if(i==cuoc){
                tinhtrang="Thắng";
                System.out.println("Số thắng: "+i);
                break;
            }
        }
        return tinhtrang;
    }
    
    public String LayLinkHinh(int n){
        String img="";
        if(n==1)
            img = "D:\\VoVanMinhTri_2001202278_BauCuaTomCa\\src\\Image\\Nai.png";
        else if(n==2)
            img = "D:\\VoVanMinhTri_2001202278_BauCuaTomCa\\src\\Image\\Bầu.png";
        else if(n==3)
            img = "D:\\VoVanMinhTri_2001202278_BauCuaTomCa\\src\\Image\\Meo.png";
        else if(n==4)
            img = "D:\\VoVanMinhTri_2001202278_BauCuaTomCa\\src\\Image\\Ca.png";
        else if(n==5)
            img = "D:\\VoVanMinhTri_2001202278_BauCuaTomCa\\src\\Image\\Cua.png";
        else 
            img = "D:\\VoVanMinhTri_2001202278_BauCuaTomCa\\src\\Image\\Tom.png";
        return img;
    }
    
    public void RandomKQ(ArrayList<Integer> dsrandom){
        Random x = new Random();
        for(int i=1;i<=3;i++)
        {
            int n = x.nextInt(6)+1;
            System.out.println(n);
            dsrandom.add(n);
            String linkimg = LayLinkHinh(n);
            ImageIcon imgicon = new ImageIcon(new ImageIcon(linkimg).getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH));
            if(i==1)
                lblKetQua1.setIcon(imgicon);
            if(i==2)
                lblKetQua2.setIcon(imgicon);
            if(i==3)
                lblKetQua3.setIcon(imgicon);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnNhap = new javax.swing.JButton();
        txtNhap = new javax.swing.JTextField();
        lblNai = new javax.swing.JLabel();
        lblBau = new javax.swing.JLabel();
        lblMeo = new javax.swing.JLabel();
        lblCa = new javax.swing.JLabel();
        lblCua = new javax.swing.JLabel();
        lblTom = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblKetQua2 = new javax.swing.JLabel();
        lblKetQua3 = new javax.swing.JLabel();
        lblKetQua1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBang = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        cboChon = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        btnQuay = new javax.swing.JButton();
        txtTienCuoc = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtTienConLai = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Số tiền bạn có:");

        btnNhap.setText("Nhập");
        btnNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapActionPerformed(evt);
            }
        });

        txtNhap.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNhapKeyTyped(evt);
            }
        });

        lblNai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Nai.png"))); // NOI18N

        lblBau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Bầu.png"))); // NOI18N

        lblMeo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Meo.png"))); // NOI18N

        lblCa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Ca.png"))); // NOI18N

        lblCua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Cua.png"))); // NOI18N

        lblTom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Tom.png"))); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Kết quả:"));
        jPanel1.setToolTipText("");

        lblKetQua2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Bầu.png"))); // NOI18N

        lblKetQua3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Meo.png"))); // NOI18N

        lblKetQua1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Nai.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(lblKetQua1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 143, Short.MAX_VALUE)
                .addComponent(lblKetQua2)
                .addGap(130, 130, 130)
                .addComponent(lblKetQua3)
                .addGap(75, 75, 75))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblKetQua1)
                    .addComponent(lblKetQua2)
                    .addComponent(lblKetQua3))
                .addContainerGap(93, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(tblBang);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Chọn:"));

        jLabel8.setText("Tiền cược:");

        btnQuay.setText("Quay");
        btnQuay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuayActionPerformed(evt);
            }
        });

        jLabel9.setText("Tiền còn lại:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(btnQuay)
                    .addComponent(txtTienCuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtTienConLai, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboChon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cboChon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTienCuoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btnQuay)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(txtTienConLai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(202, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(324, 324, 324)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btnNhap)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCua)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTom))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNai)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblBau)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblMeo)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnNhap)
                    .addComponent(txtNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBau)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNai)
                                    .addComponent(lblMeo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCua)
                                    .addComponent(lblTom)
                                    .addComponent(lblCa, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnQuayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuayActionPerformed
        // TODO add your handling code here:
        DayRandom = new ArrayList<Integer>();
        RandomKQ(DayRandom);
        laydulieuBauCua(DayRandom);
    }//GEN-LAST:event_btnQuayActionPerformed

    private void btnNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapActionPerformed
        // TODO add your handling code here:
        int sotienbanco = Integer.parseInt(txtNhap.getText().trim());
        if(sotienbanco==0)
            JOptionPane.showMessageDialog(this, "Không đc nhập 0 !");
        else if(txtNhap.getText().trim().equals(""))
            JOptionPane.showMessageDialog(this, "Không đc bỏ trống !");
        else{
            txtTienConLai.setText(sotienbanco+"");
            txtNhap.setText("");
        }
    }//GEN-LAST:event_btnNhapActionPerformed

    private void txtNhapKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNhapKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)){
            evt.consume();
        }
    }//GEN-LAST:event_txtNhapKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JBaiTapBauCuaTomCa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JBaiTapBauCuaTomCa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JBaiTapBauCuaTomCa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JBaiTapBauCuaTomCa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JBaiTapBauCuaTomCa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNhap;
    private javax.swing.JButton btnQuay;
    private javax.swing.JComboBox<String> cboChon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBau;
    private javax.swing.JLabel lblCa;
    private javax.swing.JLabel lblCua;
    private javax.swing.JLabel lblKetQua1;
    private javax.swing.JLabel lblKetQua2;
    private javax.swing.JLabel lblKetQua3;
    private javax.swing.JLabel lblMeo;
    private javax.swing.JLabel lblNai;
    private javax.swing.JLabel lblTom;
    private javax.swing.JTable tblBang;
    private javax.swing.JTextField txtNhap;
    private javax.swing.JTextField txtTienConLai;
    private javax.swing.JTextField txtTienCuoc;
    // End of variables declaration//GEN-END:variables
}
